spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
        password: 12341234
        driverClassName: org.postgresql.Driver

    flyway:
        enabled: true
        user: postgres
        password: 12341234
        schemas: public
        url: jdbc:postgresql://localhost:5432/postgres